### ISSUE TITLE
Issue while running the script

### ISSUE THREAD

**Issue by YangXiaojie1998** [ttvand/Indoor-Location-Navigation-Public#1]
Thank you for your brilliant work  in the indoor location navigation, I am so impressed of your achievement and congratulation on your champion!
I am new in this field and I am trying to understand your code, attempting to run it at first. However I met an error as follows:

Traceback (most recent call last):
  File "main.py", line 61, in <module>
    main(args.mode, args.s)
  File "main.py", line 36, in main
    sensor_errors_over_time_device.run()
  File "./src/sensor_errors_over_time_device.py", line 63, in run
    preds = pd.read_csv(absolute_fold_folder / f'preds_bag_fold_{i}.csv')
  File "/home/yangxj/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 605, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/yangxj/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/yangxj/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 814, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/yangxj/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 1045, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/yangxj/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 1862, in __init__
    self._open_handles(src, kwds)
  File "/home/yangxj/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 1357, in _open_handles
    self.handles = get_handle(
  File "/home/yangxj/anaconda3/lib/python3.8/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../Indoor-Location-Navigation-Public/Models/sensor_absolute_movement/errors cv/preds_bag_fold_0.csv'

I am not sure if I got all the necessary files, could you kindly help me with it?

**Comment by ttvand** [comment]
This error is expected, we are still working on the pipeline and will let you know when all pieces are in place - probably sometime next week
